change to lib
Qbox-project/qbx_radialmenu pull request #45
Opened 2024-02-09 18:59 UTC by StrixLuca

test yes

2024-02-09 19:28 UTC, MafewTM commented
If you're updating the locales to ox_lib locales, you need to transfer over the other locales as well. We don't want to lose them all

2024-02-09 19:41 UTC, StrixLuca commented
ah oke thanks for the info

2024-02-11 07:53 UTC, DevX32 requested changes
better mark plate as variable and use qbx.getvehicleplate

2024-02-11 07:55 UTC, DevX32 commented
and convert the closet (player and vehicle) @StrixLuca

2024-02-11 23:50 UTC, BerkieBb commented on fxmanifest.lua
> +     '@ox_lib/init.lua',
indentation is off here or under this

2024-02-11 23:50 UTC, BerkieBb commented on fxmanifest.lua
> +
this can go

2024-02-13 09:41 UTC, solareon approved these changes

2024-02-13 15:56 UTC, MafewTM approved these changes

2024-02-13 15:57 UTC, merged